package btn.chess;

public enum ChessState {
	WAITING_FOR_START_POS_SELECTION,
	WAITING_FOR_DESTINATION_POS_SELECTION,
	GAME_END,
	WAITING_FOR_RESTART_RESPONSE_WHITE,
	WAITING_FOR_RESTART_RESPONSE_BLACK
}
